### ISSUE TITLE
Type of AbraFlexi\RO::$objectName must be string (as in class Ease\Molecule)

### ISSUE THREAD

**Issue by tkohout** [Spoje-NET/php-abraflexi#49]
I updated to the latest version of the library (2.25.3) but I encountered the following error:

`Type of AbraFlexi\RO::$objectName must be string (as in class Ease\Molecule)` in the file `RO.php`

I believe the problem is that the latest version has dependency of:

```
"vitexsoftware/ease-core": "dev-main"
```

which has some recent changes (reflected in the master of this library but not in `2.25.3`). This causes this mismatch between the two libraries and gives me this type error. I know I could just point my project to dev-main of this library but that's generally not very good idea.

Please consider releasing new version or removing the dependency on `dev-main`. 

Thanks!

**Comment by Vitexus** [comment]
### Thank you very much for reporting the bug.

I apologize for the trouble caused. An up-to-date and hopefully trouble-free version has just been [released](https://github.com/Spoje-NET/php-abraflexi/releases/tag/3.2.0).

At the same time, I started reconstructing the Unit tests again so that this shame would not happen again.

@tkohout please let me know if everything is ok already.

![image](https://github.com/user-attachments/assets/6af4ae9a-9009-45fe-97f0-daf5a06bb1a1)

**Comment by tkohout** [comment]
I had a quick look and the issue is resolved. Thanks for a quick reply!
